# -*- coding: utf-8 -*-
"""untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/joaovitorjin23/d913ca019dea05a1d70d2a4d505cb53d/untitled3.ipynb
"""

# Analisador de Notas e Frequência Escolar com Geração de Relatório

def validar_nota(nota):
    """Valida se a nota está entre 0 e 10."""
    return 0 <= nota <= 10


def calcular_media_ponderada(n1, n2, n3):
    """
    Calcula a média ponderada.
    Pesos:
    AV1 = 2
    AV2 = 3
    AV3 = 5
    """
    return (n1 * 2 + n2 * 3 + n3 * 5) / 10


def determinar_situacao(media, frequencia):
    """
    Define a situação do aluno.
    """
    if frequencia < 75:
        return "Reprovado por Frequência"
    elif media >= 7:
        return "Aprovado"
    elif media >= 5:
        return "Recuperação"
    else:
        return "Reprovado por Nota"


# Lista de alunos
alunos = []

# Quantidade de alunos
qtd_alunos = int(input("Digite a quantidade de alunos: "))

# Cadastro dos alunos
for i in range(qtd_alunos):
    print(f"\n--- Cadastro do Aluno {i + 1} ---")

    nome = input("Nome: ")

    notas = []

    for j in range(1, 4):
        while True:
            nota = float(input(f"Digite a nota {j}: "))

            if validar_nota(nota):
                notas.append(nota)
                break
            else:
                print("Erro! A nota deve estar entre 0 e 10.")

    frequencia = float(input("Digite a frequência (%): "))

    media = calcular_media_ponderada(
        notas[0],
        notas[1],
        notas[2]
    )

    situacao = determinar_situacao(media, frequencia)

    aluno = {
        "nome": nome,
        "notas": notas,
        "frequencia": frequencia,
        "media": round(media, 2),
        "situacao": situacao
    }

    alunos.append(aluno)

# Relatório Final
print("\n" + "=" * 50)
print("RELATÓRIO FINAL DOS ALUNOS")
print("=" * 50)

for aluno in alunos:
    print(f"\nNome: {aluno['nome']}")
    print(f"Notas: {aluno['notas']}")
    print(f"Frequência: {aluno['frequencia']}%")
    print(f"Média: {aluno['media']}")
    print(f"Situação: {aluno['situacao']}")
    print("-" * 50)# Analisador de Notas e Frequência Escolar com Geração de Relatório

def validar_nota(nota):
    """Valida se a nota está entre 0 e 10."""
    return 0 <= nota <= 10


def calcular_media_ponderada(n1, n2, n3):
    """
    Calcula a média ponderada.
    Pesos:
    AV1 = 2
    AV2 = 3
    AV3 = 5
    """
    return (n1 * 2 + n2 * 3 + n3 * 5) / 10


def determinar_situacao(media, frequencia):
    """
    Define a situação do aluno.
    """
    if frequencia < 75:
        return "Reprovado por Frequência"
    elif media >= 7:
        return "Aprovado"
    elif media >= 5:
        return "Recuperação"
    else:
        return "Reprovado por Nota"


# Lista de alunos
alunos = []

# Quantidade de alunos
qtd_alunos = int(input("Digite a quantidade de alunos: "))

# Cadastro dos alunos
for i in range(qtd_alunos):
    print(f"\n--- Cadastro do Aluno {i + 1} ---")

    nome = input("Nome: ")

    notas = []

    for j in range(1, 4):
        while True:
            nota = float(input(f"Digite a nota {j}: "))

            if validar_nota(nota):
                notas.append(nota)
                break
            else:
                print("Erro! A nota deve estar entre 0 e 10.")

    frequencia = float(input("Digite a frequência (%): "))

    media = calcular_media_ponderada(
        notas[0],
        notas[1],
        notas[2]
    )

    situacao = determinar_situacao(media, frequencia)

    aluno = {
        "nome": nome,
        "notas": notas,
        "frequencia": frequencia,
        "media": round(media, 2),
        "situacao": situacao
    }

    alunos.append(aluno)

# Relatório Final
print("\n" + "=" * 50)
print("RELATÓRIO FINAL DOS ALUNOS")
print("=" * 50)

for aluno in alunos:
    print(f"\nNome: {aluno['nome']}")
    print(f"Notas: {aluno['notas']}")
    print(f"Frequência: {aluno['frequencia']}%")
    print(f"Média: {aluno['media']}")
    print(f"Situação: {aluno['situacao']}")
    print("-" * 50)# Analisador de Notas e Frequência Escolar com Geração de Relatório

def validar_nota(nota):
    """Valida se a nota está entre 0 e 10."""
    return 0 <= nota <= 10


def calcular_media_ponderada(n1, n2, n3):
    """
    Calcula a média ponderada.
    Pesos:
    AV1 = 2
    AV2 = 3
    AV3 = 5
    """
    return (n1 * 2 + n2 * 3 + n3 * 5) / 10


def determinar_situacao(media, frequencia):
    """
    Define a situação do aluno.
    """
    if frequencia < 75:
        return "Reprovado por Frequência"
    elif media >= 7:
        return "Aprovado"
    elif media >= 5:
        return "Recuperação"
    else:
        return "Reprovado por Nota"


# Lista de alunos
alunos = []

# Quantidade de alunos
qtd_alunos = int(input("Digite a quantidade de alunos: "))

# Cadastro dos alunos
for i in range(qtd_alunos):
    print(f"\n--- Cadastro do Aluno {i + 1} ---")

    nome = input("Nome: ")

    notas = []

    for j in range(1, 4):
        while True:
            nota = float(input(f"Digite a nota {j}: "))

            if validar_nota(nota):
                notas.append(nota)
                break
            else:
                print("Erro! A nota deve estar entre 0 e 10.")

    frequencia = float(input("Digite a frequência (%): "))

    media = calcular_media_ponderada(
        notas[0],
        notas[1],
        notas[2]
    )

    situacao = determinar_situacao(media, frequencia)

    aluno = {
        "nome": nome,
        "notas": notas,
        "frequencia": frequencia,
        "media": round(media, 2),
        "situacao": situacao
    }

    alunos.append(aluno)

# Relatório Final
print("\n" + "=" * 50)
print("RELATÓRIO FINAL DOS ALUNOS")
print("=" * 50)

for aluno in alunos:
    print(f"\nNome: {aluno['nome']}")
    print(f"Notas: {aluno['notas']}")
    print(f"Frequência: {aluno['frequencia']}%")
    print(f"Média: {aluno['media']}")
    print(f"Situação: {aluno['situacao']}")
    print("-" * 50)